"""A deterministic mock provider.

Produces plausible, role-aware "work" so the entire SAMS loop — assignment,
reasoning, tool calls, artifacts, gates, events — runs end-to-end with **zero API
keys**. Output is deterministic for a given (system, prompt) so tests are stable.
"""

from __future__ import annotations

import hashlib
from typing import Any

from ..sdk.agent import Agent, Completion
from .base import LLMProvider


def _tokens(text: str) -> int:
    return max(1, len(text) // 4)


class MockProvider(LLMProvider):
    name = "mock"

    def __init__(self, model: str = "mock-1") -> None:
        self.model = model

    async def complete(
        self,
        *,
        agent: Agent,
        system: str,
        prompt: str,
        context: Any = None,
        params: dict[str, Any] | None = None,
    ) -> Completion:
        seed = hashlib.sha256((system + "::" + prompt).encode()).hexdigest()[:8]
        role = agent.manifest.spec.role
        caps = agent.manifest.capabilities

        # Pick an output shape from the agent's primary capability family.
        family = (caps[0].split(".", 1)[0] if caps else "content")
        body = _RENDERERS.get(family, _render_generic)(agent, role, prompt, seed)

        text = body
        structured: dict[str, Any] = {}
        if family in ("content", "research", "qa", "security"):
            # Produce a couple of follow-up "fixes" so capability handlers that
            # create tasks (e.g. the SEO example) have something to work with.
            structured["fixes"] = [
                {"title": f"Follow-up: {role} item {i + 1} [{seed}]", "priority": "Medium"}
                for i in range(2)
            ]

        return Completion(
            text=text,
            markdown=text,
            tokens_in=_tokens(system + prompt),
            tokens_out=_tokens(text),
            structured=structured,
        )


def _render_code(agent: Agent, role: str, prompt: str, seed: str) -> str:
    lang = "python"
    fn = f"handle_{seed}"
    return (
        f"## {role} — implementation note\n\n"
        f"Approach for: _{prompt.strip()[:120]}_\n\n"
        f"```{lang}\n"
        f"async def {fn}(event):\n"
        f'    """Auto-generated by {agent.name} ({agent.id})."""\n'
        f"    # 1. validate inputs (idempotent — events are at-least-once)\n"
        f"    # 2. perform the unit of work\n"
        f"    # 3. emit a completion event onto the bus\n"
        f"    await emit('work.completed', {{'by': '{agent.id}'}})\n"
        f"    return True\n"
        f"```\n\n"
        f"Tests added; lints clean. Ready for review at the Security Gate.\n"
    )


def _render_research(agent: Agent, role: str, prompt: str, seed: str) -> str:
    return (
        f"## Research brief [{seed}]\n\n"
        f"**Question:** {prompt.strip()[:160]}\n\n"
        f"- Finding 1 — summarized from sources.\n"
        f"- Finding 2 — corroborated across two references.\n"
        f"- Finding 3 — open question flagged for the Whiteboard.\n\n"
        f"_Sources: [1] internal vault, [2] web. Prepared by {agent.name}._\n"
    )


def _render_design(agent: Agent, role: str, prompt: str, seed: str) -> str:
    return (
        f"## Design exploration [{seed}]\n\n"
        f"Wireframe for: {prompt.strip()[:140]}\n\n"
        f"```mermaid\nflowchart LR\n  A[Entry] --> B{{Decision}}\n  B -->|yes| C[Flow]\n  B -->|no| D[Alt]\n```\n\n"
        f"Critique: spacing on the 8px grid; status uses color + icon, never color alone.\n"
    )


def _render_generic(agent: Agent, role: str, prompt: str, seed: str) -> str:
    return (
        f"## {role} output [{seed}]\n\n"
        f"Completed work for: {prompt.strip()[:160]}\n\n"
        f"- Step 1 done\n- Step 2 done\n- Result committed to the Vault.\n"
    )


_RENDERERS = {
    "code": _render_code,
    "research": _render_research,
    "design": _render_design,
    "plan": _render_research,
    "data": _render_generic,
    "ops": _render_generic,
    "content": _render_generic,
    "qa": _render_generic,
    "security": _render_generic,
}
